# Generated by Django 5.0.2 on 2024-03-24 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_inbox_feed_comment_inbox_feed_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox_feed",
            name="friendship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbox_friendships",
                to="Accounts.friendship",
            ),
        ),
    ]
