# Generated by Django 5.0.2 on 2024-03-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_inbox_feed_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
    ]
