# Generated by Django 5.0.2 on 2024-04-05 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_author_auth_token_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox_feed',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
