# Generated by Django 5.0.2 on 2024-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectedServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.TextField()),
                ("api", models.TextField()),
                ("username", models.TextField()),
                ("password", models.TextField()),
            ],
        ),
    ]
