# Generated by Django 5.0.2 on 2024-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedserver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
